name: PotPvP
version: 1.0
main: xyz.starmc.main.Main
author: yLionCodes
depend: [ProtocolLib]
commands:
  c:
  clan:
  ranks:
  reloadbot:
  spectar:
  demote:
  tweet:
  account:
  ensinar:
  score:
  spec:
  espectar:
  aplicar:
  form:
  ano:
  info:
  data:
  dia:
  horario:
  horas:
  topclan:
  topclans:
  apply:
  bc:
  build:
  cage:
  chat:
  cc:
  clearchat:
  fly:
  gamemode:
  gm:
  go:
  stop:
  topderrotas:
  topdefeats:
  reload:
  tag:
  tell:
  tp:
  hub:
  lobby:
  ping:
  prices:
  precos:
  pvp:
  uncage:
  rules:
  topwins:
  topvitorias:
  topxp:
  reg:
  regras:
  spawn:
  twitter:
  tt:
  v:
  admin:
  youtuber:
  pro:
  tpall:
  groupset:
  setgroup:
  group:
  checkgroup: